<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    
    public function getByArticle($article_id)
    {
        $dql = "SELECT c.id, c.text, c.creationDate, c.updateDate, u.name, u.url, u.picture
        FROM AppBundle:Comment c
        JOIN c.user u
        WHERE c.active = 1 AND c.article = :article_id
        ORDER BY c.id ASC";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('article_id', $article_id);
            
        return $query->getResult();
    }
    
    public function getAll()
    {
        $dql = "SELECT c.id, c.creationDate, u.name, a.title
        FROM AppBundle:Comment c
        JOIN c.user u JOIN c.article a
        ORDER BY c.id DESC";
        $query = $this->getEntityManager()->createQuery($dql);
            
        return $query->getResult();
    }
    
}
