parameters:
#    ecl_project.example.class: ECL\ProjectBundle\Example

services:
#    ecl_project.example:
#        class: %ecl_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
