ecl_file_backoffice:
    path:  /backoffice/ficheros
    defaults: { _controller: ECLFileBundle:backoffice/Default:index }
    
ecl_file_backoffice_tree:
    path:  /backoffice/ficheros/tree
    defaults: { _controller: ECLFileBundle:backoffice/Default:getTree }
    
ecl_file_backoffice_upload:
    path:  /backoffice/ficheros/upload
    defaults: { _controller: ECLFileBundle:backoffice/Default:upload }
    
ecl_file_backoffice_remove:
    path:  /backoffice/ficheros/remove
    defaults: { _controller: ECLFileBundle:backoffice/Default:remove }