ecl_blog_rss:
    path:  /blog/rss/{tag_slug}
    defaults: { _controller: ECLBlogBundle:Rss:index, tag_slug: null }
    
user_login_github:
    path:   /user/login/github/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:User:loginGithub }

user_login_linkedin:
    path:   /user/login/linkedin/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:User:loginLinkedin }

user_login_google:
    path:   /user/login/google/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:User:loginGoogle }
    
user_login_facebook:
    path:   /user/login/facebook/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:User:loginFacebook }
    
user_login_twitter:
    path:   /user/login/twitter/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:User:loginTwitter }
    
article_redirect:
    path:   /user/redirect
    defaults: { _controller: ECLBlogBundle:User:redirectToArticle }
    
hwi_oauth_logout:
    path:   /blog/{date}/{slug}/logout
    defaults: { _controller: ECLBlogBundle:User:logout }
    
ecl_blog_homepage:
    path:  /blog/{tag_slug}/{page}
    defaults: { _controller: ECLBlogBundle:Default:index, tag_slug: null, page: null }
    requirements:
        page:  \d+   

ecl_blog_article:
    path:  /blog/{date}/{slug}
    defaults: { _controller: ECLBlogBundle:Default:show }
    
ecl_blog_comment_process_create:
    path:  /blog/{date}/{slug}/{article_id}/comment/create
    defaults: { _controller: ECLBlogBundle:Default:commentCreate }
    
ecl_blog_backoffice_articles:
    path:  /backoffice/articles
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:index }
    
ecl_blog_backoffice_articles_delete:
    path:  /backoffice/articles/{id}/delete
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:delete }
    
ecl_blog_backoffice_articles_create:
    path:  /backoffice/articles/create
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:create }
    
ecl_blog_backoffice_articles_process_create:
    path:  /backoffice/articles/process-create
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:processCreate }
    
ecl_blog_backoffice_articles_edit:
    path:  /backoffice/articles/{id}/edit
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:edit }
    
ecl_blog_backoffice_articles_process_edit:
    path:  /backoffice/articles/{id}/process-edit
    defaults: { _controller: ECLBlogBundle:backoffice/Articles:processEdit }
    
ecl_blog_backoffice_comments:
    path:  /backoffice/comments
    defaults: { _controller: ECLBlogBundle:backoffice/Comments:index }
    
ecl_blog_backoffice_comments_delete:
    path:  /backoffice/comments/{id}/delete
    defaults: { _controller: ECLBlogBundle:backoffice/Comments:delete }
    
ecl_blog_backoffice_comments_edit:
    path:  /backoffice/comments/{id}/edit
    defaults: { _controller: ECLBlogBundle:backoffice/Comments:edit }
    
ecl_blog_backoffice_comments_process_edit:
    path:  /backoffice/comments/{id}/process-edit
    defaults: { _controller: ECLBlogBundle:backoffice/Comments:processEdit }
    
ecl_blog_backoffice_tags:
    path:  /backoffice/tags
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:index }

ecl_blog_backoffice_tag_delete:
    path:  /backoffice/tags/{id}/delete
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:delete }
    
ecl_blog_backoffice_tag_create:
    path:  /backoffice/tags/create
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:create }
    
ecl_blog_backoffice_tag_process_create:
    path:  /backoffice/tags/process-create
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:processCreate }
    
ecl_blog_backoffice_tag_edit:
    path:  /backoffice/tags/{id}/edit
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:edit }
    
ecl_blog_backoffice_tag_process_edit:
    path:  /backoffice/tags/{id}/process-edit
    defaults: { _controller: ECLBlogBundle:backoffice/Tags:processEdit }
    
ecl_blog_backoffice_comments:
    path:  /backoffice/comments
    defaults: { _controller: ECLBlogBundle:backoffice/Comments:index }
    
ecl_blog_boilerplate_tag:
    path:  /blog/boilerplate/tag/{blog_tag_selected}
    defaults: { _controller: ECLBlogBundle:Boilerplate:tagCollection, blog_tag_selected: null }