ecl_contact_info_es:
    path:  /{_locale}/contacto/info
    defaults: {_controller: ECLContactBundle:Default:info }
    
ecl_contact_info_en:
    path:  /{_locale}/contact/info
    defaults: { _controller: ECLContactBundle:Default:info }
    
ecl_contact_homepage_en_redirect:
    path:  /en/contacto
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        _locale: en
        route: ecl_contact_homepage_en
        permanent: true
        
ecl_contact_homepage_es_redirect:
    path:  /es/contact
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        _locale: es
        route: ecl_contact_homepage_es
        permanent: true

ecl_contact_homepage_es:
    path:  /{_locale}/contacto
    defaults: { _controller: ECLContactBundle:Default:index }
    requirements:
        _locale: es|en
    
ecl_contact_homepage_en:
    path:  /{_locale}/contact
    defaults: { _controller: ECLContactBundle:Default:index }
    requirements:
        _locale: es|en
        
ecl_contact_submit:
    path:  /{_locale}/contacto/submit
    defaults: { _controller: ECLContactBundle:Default:submit }
    methods:  [POST]