curriculum_es:
    path:  /curriculum-vitae
    defaults: { _controller: AppBundle:Curriculum\Default:index }
        
curriculum_en:
    path:  /curriculum-vitae
    defaults: { _controller: AppBundle:Curriculum\Default:index }