root:
    path: /
    defaults: { _controller: AppBundle:home\Default:redirectRoot }
    
home:
    path:      /{_locale}/
    defaults:  { _controller: AppBundle:home\Default:index }
    requirements:
        _locale: en|es