home_routes:
    resource: "routes/home.yml"
    
social_routes:
    resource: "routes/social.yml"

sitemap:
    path:  /{_locale}/sitemap
    defaults: { _controller: AppBundle:Sitemap:index }
    requirements:
        _locale: en|es

contact_routes:
    resource: "routes/contact.yml"
    
projects_routes:
    resource: "routes/projects.yml"
    
curriculum_routes:
    resource: "routes/curriculum.yml"
    prefix: /{_locale}
    requirements:
        _locale: en|es
        
blog_routes:
    resource: "routes/blog.yml"
    prefix: /{_locale}
    requirements:
        _locale: en|es
        
backoffice_routes:
    resource: "routes/backoffice.yml"
    prefix: /{_locale}
    requirements:
        _locale: en|es