imports:
    - { resource: providers.yml }

security:
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/blog/login
            anonymous: true
            oauth:
                resource_owners:
                    my_linkedin: linkedin_login_check
                    my_github:   github_login_check
                    my_facebook: facebook_login_check
                    my_twitter:  twitter_login_check
                    my_google:   google_login_check
                check_path: social_login_check
                login_path: /blog/login
                use_forward:  false
                failure_path: /blog/login
                default_target_path: article_redirect
                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
        secured_area:
            pattern:    /backoffice
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: backoffice
                provider: my_in_memory_provider
            logout:
                path: logout
                target: login
            anonymous: true

    access_control:
        - { path: /backoffice/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /backoffice, roles: ROLE_ADMIN }
        - { path: ^/blog/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }