root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: true
        
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /blog/connect
    
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /blog/login
    
github_login_connect:
    path: /blog/connect/my_github

linkedin_login_connect:
    path: /blog/connect/my_linkedin
    
google_login_connect:
    path: /blog/connect/my_google
    
facebook_login_connect:
    path: /blog/connect/my_facebook
    
twitter_login_connect:
    path: /blog/connect/my_twitter

github_login_check:
    path: /blog/login/check-github
    
linkedin_login_check:
    path: /blog/login/check-linkedin
    
google_login_check:
    path: /blog/login/check-google
    
twitter_login_check:
    path: /blog/login/check-twitter
    
facebook_login_check:
    path: /blog/login/check-facebook
    
social_login_check:
    path: /social/login_check